# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "qbittorrentofficial/qbittorrent-nox:5.1.0-1"
  amd64: "qbittorrentofficial/qbittorrent-nox:5.1.0-1"
  armhf: "qbittorrentofficial/qbittorrent-nox:5.1.0-1"
  armv7: "qbittorrentofficial/qbittorrent-nox:5.1.0-1"
  i386: "qbittorrentofficial/qbittorrent-nox:5.1.0-1"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: qBittorrent-Wireguard"
  org.opencontainers.image.description: "qBittorrent and WireGuard with automatic Port Forwarding for ProtonVPN."
  org.opencontainers.image.source: "https://github.com/Computerdores/hassio-qbittorrent-wireguard"
  org.opencontainers.image.licenses: "GPLv3"
